
// -*- C++ -*-
// $Id: Version.h 94410 2011-08-23 17:03:34Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 0
#define ACE_BETA_VERSION 4
#define ACE_VERSION "6.0.4"
